name: Lint
on: push
jobs:
  lint-run:
    runs-on: ubuntu-latest
    steps:
      - steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run lint
